ALTER TABLE users ADD COLUMN display_language VARCHAR(20) NOT NULL DEFAULT 'en';
ALTER TABLE users ADD COLUMN native_language VARCHAR(20) NOT NULL DEFAULT 'en';
ALTER TABLE users ADD COLUMN target_level VARCHAR(30) NOT NULL DEFAULT 'BEGINNER_2';
